Extractor update for 1.13
PrismarineJS/burger-extractor pull request #1
Opened 2018-08-25 10:48 UTC by lluiscab

I've updated the extractor so it correctly gets all required data.
https://github.com/Pokechu22/Burger/tree/1.13-fixes

2018-08-28 17:47 UTC, rom1504 commented
Can you add standard (npm install --saveDev standard and add standard in the test script in package.json) and run standard --fix ?

2018-08-28 18:56 UTC, lluiscab commented
yep, didn't really have this here to my IDE config just took over the standard. Will do tomorrow

2018-08-29 09:18 UTC, lluiscab commented
Just standardized the code.

2018-09-01 16:18 UTC, rom1504 requested changes
looks ok but let's wait for the mcdata PR to be done before merging this as it might require changes here too

2018-09-01 16:18 UTC, rom1504 commented on README.md
> +[minecraft-data](https://github.com/PrismarineJS/minecraft-data) json files.
Please keep the information on what files it generates. It doesn't generate everything in Minecraft data

2018-09-01 17:52 UTC, lluiscab commented on README.md
> +[minecraft-data](https://github.com/PrismarineJS/minecraft-data) json files.
Okay

2018-09-01 17:52 UTC, lluiscab commented
Okay, just wanted to get the PR started here.

2018-09-24 19:41 UTC, merged